global:
  enabled: true
  tlsDisable: false
server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault2/ca.pem
  extraVolumes:
  - name: vault2
    type: secret
  ha:
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        tls_disable = "false"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault2/vault.pem"
        tls_key_file  = "/vault/userconfig/vault2/vault-key.pem"
        tls_client_ca_file = "/vault/userconfig/vault2/ca.pem"
      }
      storage "consul" {
        path = "vault/"
        scheme = "https"
        address = "HOST_IP:8501"
        disable_registration = "false"
        tls_skip_verify = "true"
        tls_cert_file = "/vault/userconfig/vault2/vault.pem"
        tls_key_file  = "/vault/userconfig/vault2/vault-key.pem"
        tls_ca_file = "/vault/userconfig/vault2/ca.pem"
      }
      service_registration "kubernetes" {}
    enabled: true
  ingress:
    annotations: |
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - host: cluster.local
      paths:
      - /
      - /vault
    tls:
    - hosts:
      - cluster.local
      secretName: vault2
ui:
  enabled: true
  externalPort: 8200
  serviceNodePort: null
  serviceType: LoadBalancer
